// <auto-generated />
namespace Team11_SSIS_ADProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changestatusintointegerindepartmentdelegation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changestatusintointegerindepartmentdelegation));
        
        string IMigrationMetadata.Id
        {
            get { return "202002090725420_change status into integer in department delegation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
