// <auto-generated />
namespace Team11_SSIS_ADProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_required_to_item_attributes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_required_to_item_attributes));
        
        string IMigrationMetadata.Id
        {
            get { return "202001190834500_add_required_to_item_attributes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
