// <auto-generated />
namespace Team11_SSIS_ADProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class remove_startingqty_from_item : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_startingqty_from_item));
        
        string IMigrationMetadata.Id
        {
            get { return "202001190822448_remove_startingqty_from_item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
